### ISSUE TITLE
Package is not creating a UI

### ISSUE THREAD

**Issue by torrmercury** [LukasHechenberger/atom-json-editor#4]
I've been trying to use the package and make a UI by making an example file "package.json" in order to use the example schema but the UI does not build. The readme is vague and unhelpful in figuring out what I need to do to build the UI or if there's a bug.

**Comment by LukasHechenberger** [comment]
I just re-installed the package and followed the steps you described but everything seems to work fine.
The only issue i expected was **when the package.json-file is open while installing** the package. You just have to de- and reselect the tab with the file in this case.

Does this prevent the issue?

**Comment by torrmercury** [comment]
Yea I'm not sure what's going on with that. I just tried uninstalling and then reinstalling the package without any tabs open, and then opened the package.json file, and the gui still doesn't come up. Is it possible that the package is not working right with my version of Atom (should be the latest)?

**Comment by LukasHechenberger** [comment]
I'm working on 1.2.4 (definitely the latest).

**Comment by torrmercury** [comment]
Ok so I finally had time to try this again, and this time, I'm getting errors:

EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
    at Function (native)
    at Function.line.toFunction (C:\Users\mchen.atom\packages\json-schema\node_modules\is-my-json-valid\node_modules\generate-function\index.js:55:21)
    at compile (C:\Users\mchen.atom\packages\json-schema\node_modules\is-my-json-valid\index.js:543:23)
    at visit (C:\Users\mchen.atom\packages\json-schema\node_modules\is-my-json-valid\index.js:326:16)
    at C:\Users\mchen.atom\packages\json-schema\node_modules\is-my-json-valid\index.js:523:9
    at Array.forEach (native)
    at visit (C:\Users\mchen.atom\packages\json-schema\node_modules\is-my-json-valid\index.js:520:31)
    at compile (C:\Users\mchen.atom\packages\json-schema\node_modules\is-my-json-valid\index.js:537:3)
    at visit (C:\Users\mchen.atom\packages\json-schema\node_modules\is-my-json-valid\index.js:326:16)
    at C:\Users\mchen.atom\packages\json-schema\node_modules\is-my-json-valid\index.js:388:9
    at Array.forEach (native)
    at visit (C:\Users\mchen.atom\packages\json-schema\node_modules\is-my-json-valid\index.js:387:18)
    at compile (C:\Users\mchen.atom\packages\json-schema\node_modules\is-my-json-valid\index.js:537:3)
    at module.exports (C:\Users\mchen.atom\packages\json-schema\node_modules\is-my-json-valid\index.js:566:10)
    at C:\Users\mchen.atom\packages\json-schema\lib\schema-linter.js:52:12
    at memoized (C:\Users\mchen\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:7912:27)
    at MapObservable.selector (C:\Users\mchen.atom\packages\json-schema\lib\schema-linter.js:63:49)
    at C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:4785:67
    at tryCatcher (C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:567:29)
    at InnerObserver.onNext (C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:4806:43)
    at InnerObserver.tryCatcher (C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:567:29)
    at AutoDetachObserverPrototype.next (C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:5274:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:1710:35)
    at InnerObserver.onNext (C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:3627:90)
    at InnerObserver.tryCatcher (C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:567:29)
    at AutoDetachObserverPrototype.next (C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:5274:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:1710:35)
    at C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:1855:51
    at C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:1884:13
    at scheduleInnerRecursive (C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:1085:7)
    at recursiveAction (C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:1039:9)
    at [object Object].invokeRecImmediate [as action](C:Usersmchen.atompackagesjson-schemanode_modulesrxdistrx.js:1056:7)
    at [object Object].ScheduledItem.invokeCore (C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:929:17)
    at [object Object].ScheduledItem.invoke (C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:917:40)
    at runTrampoline (C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:1237:37)
    at tryCatcher (C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:567:29)
    at Scheduler.scheduleNow [as _schedule](C:Usersmchen.atompackagesjson-schemanode_modulesrxdistrx.js:1248:45)
    at Scheduler.Rx.Scheduler.schedulerProto.scheduleWithState (C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:970:19)
    at Scheduler.schedulerProto.scheduleRecursiveWithState (C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:1104:19)
    at Scheduler.schedulerProto.scheduleRecursive (C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:1094:19)
    at ScheduledObserver.Rx.internals.ScheduledObserver.ScheduledObserver.ensureActive (C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:1875:54)
    at ReplaySubject.Rx.ReplaySubject.addProperties.onNext (C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.binding.js:410:20)
    at ReplaySubject.tryCatcher (C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:567:29)
    at AutoDetachObserverPrototype.next (C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:5274:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:1710:35)
    at AutoDetachObserver.tryCatcher (C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:567:29)
    at AutoDetachObserverPrototype.next (C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:5274:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:1710:35)
    at C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:2323:7
    at process._tickCallback (node.js:368:9)

**Comment by torrmercury** [comment]
The other error is:

EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
    at Function (native)
    at Function.line.toFunction (C:\Users\mchen.atom\packages\json-schema\node_modules\is-my-json-valid\node_modules\generate-function\index.js:55:21)
    at compile (C:\Users\mchen.atom\packages\json-schema\node_modules\is-my-json-valid\index.js:543:23)
    at visit (C:\Users\mchen.atom\packages\json-schema\node_modules\is-my-json-valid\index.js:326:16)
    at C:\Users\mchen.atom\packages\json-schema\node_modules\is-my-json-valid\index.js:523:9
    at Array.forEach (native)
    at visit (C:\Users\mchen.atom\packages\json-schema\node_modules\is-my-json-valid\index.js:520:31)
    at compile (C:\Users\mchen.atom\packages\json-schema\node_modules\is-my-json-valid\index.js:537:3)
    at visit (C:\Users\mchen.atom\packages\json-schema\node_modules\is-my-json-valid\index.js:326:16)
    at C:\Users\mchen.atom\packages\json-schema\node_modules\is-my-json-valid\index.js:388:9
    at Array.forEach (native)
    at visit (C:\Users\mchen.atom\packages\json-schema\node_modules\is-my-json-valid\index.js:387:18)
    at compile (C:\Users\mchen.atom\packages\json-schema\node_modules\is-my-json-valid\index.js:537:3)
    at module.exports (C:\Users\mchen.atom\packages\json-schema\node_modules\is-my-json-valid\index.js:566:10)
    at C:\Users\mchen.atom\packages\json-schema\lib\schema-linter.js:52:12
    at memoized (C:\Users\mchen\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:7912:27)
    at MapObservable.selector (C:\Users\mchen.atom\packages\json-schema\lib\schema-linter.js:63:49)
    at C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:4785:67
    at tryCatcher (C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:567:29)
    at InnerObserver.onNext (C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:4806:43)
    at InnerObserver.tryCatcher (C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:567:29)
    at AutoDetachObserverPrototype.next (C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:5274:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:1710:35)
    at InnerObserver.onNext (C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:3627:90)
    at InnerObserver.tryCatcher (C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:567:29)
    at AutoDetachObserverPrototype.next (C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:5274:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:1710:35)
    at C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:1855:51
    at C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:1884:13
    at scheduleInnerRecursive (C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:1085:7)
    at recursiveAction (C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:1039:9)
    at [object Object].invokeRecImmediate [as action](C:Usersmchen.atompackagesjson-schemanode_modulesrxdistrx.js:1056:7)
    at [object Object].ScheduledItem.invokeCore (C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:929:17)
    at [object Object].ScheduledItem.invoke (C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:917:40)
    at runTrampoline (C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:1237:37)
    at tryCatcher (C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:567:29)
    at Scheduler.scheduleNow [as _schedule](C:Usersmchen.atompackagesjson-schemanode_modulesrxdistrx.js:1248:45)
    at Scheduler.Rx.Scheduler.schedulerProto.scheduleWithState (C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:970:19)
    at AnonymousObservable.s [as _subscribe](C:Usersmchen.atompackagesjson-schemanode_modulesrxdistrx.js:5248:34)
    at AnonymousObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:1976:19)
    at C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:2358:14
    at AnonymousObservable.observableProto.toPromise (C:\Users\mchen.atom\packages\json-schema\node_modules\rx\dist\rx.js:2355:12)
    at Object.exports.provider.lint (C:\Users\mchen.atom\packages\json-schema\lib\schema-linter.js:81:18)
    at promises.push.Promise.then._this.emitter.emit.linter (C:/Users/mchen/.atom/packages/linter/lib/linter-registry.js:63:26)
    at C:/Users/mchen/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (C:/Users/mchen/.atom/packages/linter/lib/linter-registry.js:60:18)
    at file:///C:/Users/mchen/.atom/packages/linter/lib/linter.coffee:98:16
    at Emitter.module.exports.Emitter.emit (C:\Users\mchen\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at C:/Users/mchen/.atom/packages/linter/lib/editor-linter.js:80:22
    at file:///C:/Users/mchen/.atom/packages/linter/lib/helpers.coffee:23:18
